name: 'Update Docker Hub Descriptions'
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/DockerHubDescription.yml
jobs:
  description:
    name: 'Update Docker Hub Descriptions'
    runs-on: ubuntu-latest
    steps:

      # https://github.com/marketplace/actions/checkout
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/docker-hub-description
      - name: 'Update Docker Hub Description'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ptr727/vscode-server-dotnetcore
